#!/bin/sh

SCULL_MODULE=/lib/modules/$(uname -r)/updates/scull.ko

case "$1" in
    start)
        echo "Loading scull module"
        if [ -f ${SCULL_MODULE} ]; then
            insmod ${SCULL_MODULE} && echo "scull loaded"
        else
            modprobe scull && echo "scull loaded"
        fi
        ;;
    stop)
        echo "Unloading scull module"
        rmmod scull 2>/dev/null && echo "scull unloaded"
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
